/**
 * Compile a Design to infrastructure config.
 *
 * These are faithful *structural* translations — every node and edge shows up —
 * meant as a starting point a human finishes, not `apply`-ready output. Both
 * generators lead with a header saying exactly that, so no one mistakes Duet for
 * a provisioning tool.
 */
import { kindMeta } from './catalog';
import type { Design, DuetNode } from './types';

const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '') || 'node';

function uniqueSlugs(nodes: DuetNode[]): Map<string, string> {
  const used = new Set<string>();
  const map = new Map<string, string>();
  for (const n of nodes) {
    let base = slug(n.label);
    let name = base;
    let i = 2;
    while (used.has(name)) name = `${base}_${i++}`;
    used.add(name);
    map.set(n.id, name);
  }
  return map;
}

const COMPOSE_IMAGE: Partial<Record<DuetNode['kind'], (n: DuetNode) => string>> = {
  service: () => 'your-org/app:latest',
  worker: () => 'your-org/worker:latest',
  datastore: (n) =>
    n.props.engine === 'mysql'
      ? 'mysql:8'
      : n.props.engine === 'mongodb'
        ? 'mongo:7'
        : 'postgres:16',
  cache: (n) => (n.props.engine === 'memcached' ? 'memcached:1.6' : 'redis:7'),
  queue: (n) => (n.props.engine === 'kafka' ? 'bitnami/kafka:3.7' : 'rabbitmq:3-management'),
};

export function toDockerCompose(design: Design): string {
  const names = uniqueSlugs(design.nodes);
  const runnable = design.nodes.filter((n) => COMPOSE_IMAGE[n.kind]);
  const lines: string[] = [];
  lines.push(`# ${design.name} — docker-compose sketch generated by Duet`);
  lines.push(`# Structural translation of the canvas. Fill in images, env, and volumes before use.`);
  lines.push('');
  lines.push('services:');
  if (!runnable.length) lines.push('  {}');
  for (const n of runnable) {
    const name = names.get(n.id)!;
    const deps = design.edges
      .filter((e) => e.source === n.id)
      .map((e) => names.get(e.target))
      .filter((d): d is string => Boolean(d) && runnable.some((r) => names.get(r.id) === d));
    lines.push(`  ${name}:`);
    lines.push(`    image: ${COMPOSE_IMAGE[n.kind]!(n)}`);
    if (n.kind === 'service' || n.kind === 'worker') {
      const replicas = n.props.replicas ?? 1;
      if (replicas > 1) {
        lines.push(`    deploy:`);
        lines.push(`      replicas: ${replicas}`);
      }
      if (n.kind === 'service' && n.props.publicIngress) lines.push(`    ports: ['8080:8080']`);
    }
    if (deps.length) {
      lines.push(`    depends_on: [${[...new Set(deps)].join(', ')}]`);
    }
    lines.push('');
  }
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

const TF_TYPE: Record<DuetNode['kind'], string> = {
  client: 'null_resource',
  cdn: 'aws_cloudfront_distribution',
  loadbalancer: 'aws_lb',
  service: 'aws_ecs_service',
  worker: 'aws_ecs_service',
  queue: 'aws_sqs_queue',
  datastore: 'aws_db_instance',
  cache: 'aws_elasticache_cluster',
  objectstore: 'aws_s3_bucket',
  external: 'null_resource',
};

export function toTerraformSketch(design: Design): string {
  const names = uniqueSlugs(design.nodes);
  const out: string[] = [];
  out.push(`# ${design.name} — Terraform sketch generated by Duet`);
  out.push(`# A structural starting point, NOT apply-ready: no providers, IAM, networking,`);
  out.push(`# or required arguments are included. Region: ${design.region || 'us-east-1'}`);
  out.push('');
  for (const n of design.nodes) {
    const name = names.get(n.id)!;
    const type = TF_TYPE[n.kind];
    out.push(`# ${kindMeta(n.kind).label}: ${n.label}`);
    out.push(`resource "${type}" "${name}" {`);
    out.push(`  # duet:kind = ${n.kind}`);
    for (const [k, v] of Object.entries(n.props)) {
      if (v === undefined || v === '' || v === false) continue;
      out.push(`  # ${k} = ${JSON.stringify(v)}`);
    }
    const deps = design.edges
      .filter((e) => e.source === n.id)
      .map((e) => `${TF_TYPE[design.nodes.find((x) => x.id === e.target)?.kind ?? 'client']}.${names.get(e.target)}`)
      .filter(Boolean);
    if (deps.length) out.push(`  depends_on = [${[...new Set(deps)].join(', ')}]`);
    out.push('}');
    out.push('');
  }
  return out.join('\n').trimEnd() + '\n';
}

export type IacFormat = 'compose' | 'terraform';

export function compile(design: Design, format: IacFormat): { filename: string; body: string } {
  return format === 'compose'
    ? { filename: 'docker-compose.yml', body: toDockerCompose(design) }
    : { filename: 'main.tf', body: toTerraformSketch(design) };
}
